[project]
name = "minimind"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "peiqi", email = "20021028pq@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "datasets>=5.0.1",
    "modelscope>=1.40.0",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "swanlab>=0.10.0",
    "torch>=2.9.0",
    "transformers>=4.57.1",
]

[project.scripts]
minimind = "minimind:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

